# -- 코드를 입력하세요
# SELECT J.CAR_ID, J.CAR_TYPE, FLOOR(((J.DAILY_FEE * (100 - P.DISCOUNT_RATE)/100 ) * 30)) FEE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P, (SELECT distinct(H.CAR_ID), A.CAR_TYPE, A.DAILY_FEE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR A
#     WHERE ((H.END_DATE <= '2022-11-30') AND (H.START_DATE >= '2022-11-01'))
#                AND(A.CAR_ID = H.CAR_ID)) A, CAR_RENTAL_COMPANY_CAR J
# WHERE P.DURATION_TYPE = '30일 이상' AND J.CAR_TYPE IN ('세단', 'SUV')
# AND FLOOR(((J.DAILY_FEE * (100 - P.DISCOUNT_RATE)/100 ) * 30)) BETWEEN 500000 AND 2000000
# AND A.CAR_ID != J.CAR_ID
# ORDER BY FEE DESC, J.CAR_TYPE, J.CAR_ID DESC

SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(((A.DAILY_FEE * (100 - C.DISCOUNT_RATE)/100 ) * 30)) FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
LEFT JOIN (SELECT CAR_ID 
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                       WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')) B ON A.CAR_ID = B.CAR_ID
WHERE
    B.CAR_ID IS NULL
    AND
    FLOOR(((A.DAILY_FEE * (100 - C.DISCOUNT_RATE)/100 ) * 30)) BETWEEN 500000 AND 2000000
    AND
    C.DURATION_TYPE = '30일 이상' 
    AND 
    A.CAR_TYPE IN ('세단', 'SUV')
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC

