-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성해주세요. 이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬해주세요.
SELECT O.PRODUCT_ID, O.PRODUCT_NAME, (PR.AM * O.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT O
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AM 
      FROM FOOD_ORDER
     WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
     GROUP BY PRODUCT_ID) PR
WHERE O.PRODUCT_ID = PR.PRODUCT_ID
ORDER BY (PR.AM * O.PRICE) DESC, O.PRODUCT_ID


# SELECT PRODUCT_ID, SUM(AMOUNT) AM 
#       FROM FOOD_ORDER
#      WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-30'
#      GROUP BY PRODUCT_ID
     
     
# SELECT *
# FROM FOOD_ORDER F, FOOD_PRODUCT P
# WHERE F.PRODUCT_ID = P.PRODUCT_ID
# AND F.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-30'